default: &default
  host: localhost
  adapter: postgresql
  pool: 5
  timeout: 5000

development:  
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: cl0ud9_dev
  pool: 5
  username: postgres
  password: postgres

test: &test
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: cl0ud9_test
  pool: 5
  username: postgres
  password: postgres

cucumber:
  <<: *test
