default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:  
  adapter: postgresql
  encoding: unicode
  database: cl0ud9_dev
  pool: 5
  username: postgres
  password: postgres

test:  
  adapter: postgresql
  encoding: unicode
  database: cl0ud9_test
  pool: 5
  username: postgres
  password: postgres
