# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)

#ZS:adding the admin account info
p = Person.create!(password: '123abc', fName: 'cloud9', lName: 'admin', birthDate: Date.parse('1920/8/20'), email: 'cloud9golfing@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@cl0ud9golf', fbLink: 'https://www.facebook.com/Cl0ud9Golf/')
p.update_column(:profilePicLink,'og1.jpg')
p = Person.create!(password: '123abc', fName: 'Ozell', lName: 'Snavely', birthDate: Date.parse('1917/6/1'), email: 'Ozell.Snavely@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og2.jpg')
p = Person.create!(password: '123abc', fName: 'Lawrence', lName: 'Medford', birthDate: Date.parse('1979/2/22'), email: 'Lawrence.Medford@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og3.jpg')
p = Person.create!(password: '123abc', fName: 'Ezequiel', lName: 'Crosswell', birthDate: Date.parse('1930/11/10'), email: 'Ezequiel.Crosswell@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og4.jpg')
p = Person.create!(password: '123abc', fName: 'Karrie', lName: 'Mccaw', birthDate: Date.parse('1912/3/16'), email: 'Karrie.Mccaw@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og5.jpg')
p = Person.create!(password: '123abc', fName: 'Cassidy', lName: 'Capello', birthDate: Date.parse('1971/12/20'), email: 'Cassidy.Capello@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og6.jpg')
p = Person.create!(password: '123abc', fName: 'Jamison', lName: 'Osmun', birthDate: Date.parse('1918/2/10'), email: 'Jamison.Osmun@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og7.jpg')
p = Person.create!(password: '123abc', fName: 'Keila', lName: 'Sison', birthDate: Date.parse('1911/8/13'), email: 'Keila.Sison@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og1.jpg')
p = Person.create!(password: '123abc', fName: 'Mattie', lName: 'Goodspeed', birthDate: Date.parse('1969/3/23'), email: 'Mattie.Goodspeed@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og2.jpg')
p = Person.create!(password: '123abc', fName: 'Lahoma', lName: 'Missildine', birthDate: Date.parse('1900/5/14'), email: 'Lahoma.Missildine@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og3.jpg')
p = Person.create!(password: '123abc', fName: 'Yen', lName: 'Lynn', birthDate: Date.parse('1907/5/24'), email: 'Yen.Lynn@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og4.jpg')
p = Person.create!(password: '123abc', fName: 'Barabara', lName: 'Cecena', birthDate: Date.parse('1983/8/9'), email: 'Barabara.Cecena@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og5.jpg')
p = Person.create!(password: '123abc', fName: 'Marica', lName: 'Mcquire', birthDate: Date.parse('1989/8/9'), email: 'Marica.Mcquire@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og6.jpg')
p = Person.create!(password: '123abc', fName: 'Codi', lName: 'Gaumer', birthDate: Date.parse('1931/6/4'), email: 'Codi.Gaumer@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og7.jpg')

g = GolfCourse.create!(name: 'Dancing Sheep Golf Club', phone: 1234567890, addrStreetNum: 20, addrUnitNum: nil, addrStreetName: 'Vanauley Street', addrPostalCode: 'M5T 2H4', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'DancingSheep@golf.com', capacity:400 )
g.update_column(:logoLink, 'gc1.png')
g = GolfCourse.create!(name: 'Walking Albatross Golf Club', phone: 1234567111, addrStreetNum: 5950, addrUnitNum: nil, addrStreetName: 'ON HWY 540', addrPostalCode: 'P0P 1G0', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'WalkingAlbatross@golf.com', capacity:400 )
g.update_column(:logoLink, 'gc2.png')
g = GolfCourse.create!(name: 'Sleeping Toad Golf Club', phone: 1244467890, addrStreetNum: 2329, addrUnitNum: nil, addrStreetName: 'West Mall', addrPostalCode: 'V6T 1Z4', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'SleepingToad@golf.com', capacity:401 )
g.update_column(:logoLink, 'gc3.png')
g = GolfCourse.create!(name: 'Waving Fish Golf Club', phone: 1223423890, addrStreetNum: 200, addrUnitNum: nil, addrStreetName: 'St George St.', addrPostalCode: 'M2J 1P1', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'WavingFish@golf.com', capacity:200 )
g.update_column(:logoLink, 'gc4.png')
g = GolfCourse.create!(name: 'Stomping Petites Golf Club', phone: 1231111890, addrStreetNum: 222, addrUnitNum: nil, addrStreetName: 'Elm St', addrPostalCode: 'M2J 0P9', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'StompingPetites@golf.com', capacity:50 )
g.update_column(:logoLink, 'gc5.png')
g = GolfCourse.create!(name: 'Arnold Palmer Golf Club', phone: 1239999890, addrStreetNum: 10, addrUnitNum: nil, addrStreetName: 'Baker St', addrPostalCode: 'M2J 5P1', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'ArnoldPalmer@golf.com', capacity:100 )
g.update_column(:logoLink, 'gc6.png')

Host.create!(hostName: 'Golf Association of Hawaii', phone: 0010002222, email: 'gah@golf.com')
Host.create!(hostName: 'Society for Overworked Golf Players', phone: 0033302222, email: 'sogp@golf.com')
Host.create!(hostName: 'Make-A-Wish Foundation', phone: 0011112222, email: 'mawf@charity.com')
Host.create!(hostName: 'Kiwanis Club', phone: 1110002222, email: 'kc@charity.com')

t = Tournament.create!(name: 'Make-A-Wish Foundation Fall Fundraiser', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("09/01/20 17:00", "%m/%d/%Y %H:%M"), numGuests: 100, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST',  registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 3, golf_course_id: 1)
t.update_column(:logoLink, 'puppy.jpg')
t = Tournament.create!(name: 'Golf Association of Hawaii', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("09/01/2009 17:00", "%m/%d/%Y %H:%M"), numGuests: 100, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 2, golf_course_id: 2)
t.update_column(:logoLink, 'puppy.jpg')
t = Tournament.create!(name: 'Society for Overworked Golf Player', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("09/01/2009 17:00", "%m/%d/%Y %H:%M"), numGuests: 100, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 3, golf_course_id: 3)
t.update_column(:logoLink, 'puppy.jpg')
t = Tournament.create!(name: 'Test', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("09/01/2009 17:00", "%m/%d/%Y %H:%M"), numGuests: 1, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 3, golf_course_id: 3)
t.update_column(:logoLink, 'puppy.jpg')

t = TicketType.create!(tournament_id: 1, name: 'Single', price: 50.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 1, name: 'Foursome', price: 175.00, numPlayers: 4)
t = TicketType.create!(tournament_id: 2, name: 'Single',  price: 50.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 2, name: 'Foursome',  price: 175.00, numPlayers: 4)
t = TicketType.create!(tournament_id: 3, name: 'Single', price: 50.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 3, name: 'Foursome',  price: 175.00, numPlayers: 4)

t = TicketType.create!(tournament_id: 4, name: 'Single',  price: 50.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 4, name: 'Foursome',  price: 175.00, numPlayers: 4)
