# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)

#ZS:adding the admin account info
p = Person.create!(password: '123abc', fName: 'cloud9', lName: 'admin', birthDate: Date.parse('1920/8/20'), email: 'cloud9golfing@gmail.com', allowUserEmails: 'true', profilePicLink: 'og1.jpg', twitterLink: '@cl0ud9golf', fbLink: 'https://www.facebook.com/Cl0ud9Golf/')
p.update_column(:profilePicLink,'og1.jpg')
p = Person.create!(password: '123abc', fName: 'Ozell', lName: 'Snavely', birthDate: Date.parse('1917/6/1'), email: 'Ozell.Snavely@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og2.jpg')
p = Person.create!(password: '123abc', fName: 'Lawrence', lName: 'Medford', birthDate: Date.parse('1979/2/22'), email: 'Lawrence.Medford@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og3.jpg')
p = Person.create!(password: '123abc', fName: 'Ezequiel', lName: 'Crosswell', birthDate: Date.parse('1930/11/10'), email: 'Ezequiel.Crosswell@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og4.jpg')
p = Person.create!(password: '123abc', fName: 'Karrie', lName: 'Mccaw', birthDate: Date.parse('1912/3/16'), email: 'Karrie.Mccaw@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og5.jpg')
p = Person.create!(password: '123abc', fName: 'Cassidy', lName: 'Capello', birthDate: Date.parse('1971/12/20'), email: 'Cassidy.Capello@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og6.jpg')
p = Person.create!(password: '123abc', fName: 'Jamison', lName: 'Osmun', birthDate: Date.parse('1918/2/10'), email: 'Jamison.Osmun@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og7.jpg')
p = Person.create!(password: '123abc', fName: 'Keila', lName: 'Sison', birthDate: Date.parse('1911/8/13'), email: 'Keila.Sison@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og1.jpg')
p = Person.create!(password: '123abc', fName: 'Mattie', lName: 'Goodspeed', birthDate: Date.parse('1969/3/23'), email: 'Mattie.Goodspeed@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og2.jpg')
p = Person.create!(password: '123abc', fName: 'Lahoma', lName: 'Missildine', birthDate: Date.parse('1900/5/14'), email: 'Lahoma.Missildine@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og3.jpg')
p = Person.create!(password: '123abc', fName: 'Yen', lName: 'Lynn', birthDate: Date.parse('1907/5/24'), email: 'Yen.Lynn@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og4.jpg')
p = Person.create!(password: '123abc', fName: 'Barabara', lName: 'Cecena', birthDate: Date.parse('1983/8/9'), email: 'Barabara.Cecena@gmail.com', allowUserEmails: 'false', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og5.jpg')
p = Person.create!(password: '123abc', fName: 'Marica', lName: 'Mcquire', birthDate: Date.parse('1989/8/9'), email: 'Marica.Mcquire@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og6.jpg')
p = Person.create!(password: '123abc', fName: 'Codi', lName: 'Gaumer', birthDate: Date.parse('1931/6/4'), email: 'Codi.Gaumer@gmail.com', allowUserEmails: 'true', profilePicLink: 'puppy.jpg', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p.update_column(:profilePicLink,'og7.jpg')
p = Person.create!(password: '123abc', fName: 'Nicki', lName: 'Bowne', birthDate: Date.parse('1940/8/4'), email: 'Nicki.Bowne@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Grisel', lName: 'Leeder', birthDate: Date.parse('1980/12/9'), email: 'Grisel.Leeder@gmail.com', allowUserEmails: 'false', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Yuette', lName: 'Cambareri', birthDate: Date.parse('2000/11/23'), email: 'Yuette.Cambareri@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Rayna', lName: 'Ruppel', birthDate: Date.parse('1953/6/5'), email: 'Rayna.Ruppel@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Linnea', lName: 'Crosswell', birthDate: Date.parse('1972/1/22'), email: 'Linnea.Crosswell@gmail.com', allowUserEmails: 'false', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Rosamaria', lName: 'Fickel', birthDate: Date.parse('1990/2/10'), email: 'Rosamaria.Fickel@gmail.com', allowUserEmails: 'false', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Beula', lName: 'Getty', birthDate: Date.parse('1972/6/22'), email: 'Beula.Getty@gmail.com', allowUserEmails: 'false', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Heath', lName: 'Valla', birthDate: Date.parse('1919/9/26'), email: 'Heath.Valla@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Holli', lName: 'Bockman', birthDate: Date.parse('1974/11/3'), email: 'Holli.Bockman@gmail.com', allowUserEmails: 'false', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Josh', lName: 'Slattery', birthDate: Date.parse('1981/12/12'), email: 'Josh.Slattery@gmail.com', allowUserEmails: 'false', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Leeanne', lName: 'Redinger', birthDate: Date.parse('1914/6/24'), email: 'Leeanne.Redinger@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Solange', lName: 'Shipton', birthDate: Date.parse('1952/10/18'), email: 'Solange.Shipton@gmail.com', allowUserEmails: 'false', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Rufina', lName: 'Flanders', birthDate: Date.parse('1944/5/20'), email: 'Rufina.Flanders@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Scottie', lName: 'Wygant', birthDate: Date.parse('1981/9/6'), email: 'Scottie.Wygant@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Sharmaine', lName: 'Baxter', birthDate: Date.parse('1931/10/29'), email: 'Sharmaine.Baxter@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Meaghan', lName: 'To', birthDate: Date.parse('1999/8/18'), email: 'Meaghan.To@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Lawanda', lName: 'Fucci', birthDate: Date.parse('1972/8/14'), email: 'Lawanda.Fucci@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')
p = Person.create!(password: '123abc', fName: 'Lakiesha', lName: 'Carreno', birthDate: Date.parse('1933/6/2'), email: 'Lakiesha.Carreno@gmail.com', allowUserEmails: 'true', profilePicLink: 'default_user_rsqx3z.png', twitterLink: '@ThatKevinSmith', fbLink: 'https://www.facebook.com/ellentv/?fref=ts')


g = GolfCourse.create!(name: 'Dancing Sheep Golf Club', phone: 1234567890, addrStreetNum: 20, addrUnitNum: nil, addrStreetName: 'Vanauley Street', addrPostalCode: 'M5T 2H4', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'DancingSheep@golf.com', capacity:400 )
g.update_column(:logoLink, 'gc1.png')
g = GolfCourse.create!(name: 'Walking Albatross Golf Club', phone: 1234567111, addrStreetNum: 5950, addrUnitNum: nil, addrStreetName: 'ON HWY 540', addrPostalCode: 'P0P 1G0', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'WalkingAlbatross@golf.com', capacity:400 )
g.update_column(:logoLink, 'gc2.png')
g = GolfCourse.create!(name: 'Sleeping Toad Golf Club', phone: 1244467890, addrStreetNum: 2329, addrUnitNum: nil, addrStreetName: 'West Mall', addrPostalCode: 'V6T 1Z4', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'SleepingToad@golf.com', capacity:401 )
g.update_column(:logoLink, 'gc3.png')
g = GolfCourse.create!(name: 'Waving Fish Golf Club', phone: 1223423890, addrStreetNum: 200, addrUnitNum: nil, addrStreetName: 'St George St.', addrPostalCode: 'M2J 1P1', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'WavingFish@golf.com', capacity:200 )
g.update_column(:logoLink, 'gc4.png')
g = GolfCourse.create!(name: 'Stomping Petites Golf Club', phone: 1231111890, addrStreetNum: 222, addrUnitNum: nil, addrStreetName: 'Elm St', addrPostalCode: 'M2J 0P9', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'StompingPetites@golf.com', capacity:50 )
g.update_column(:logoLink, 'gc5.png')
g = GolfCourse.create!(name: 'Arnold Palmer Golf Club', phone: 1239999890, addrStreetNum: 10, addrUnitNum: nil, addrStreetName: 'Baker St', addrPostalCode: 'M2J 5P1', addrCountry: 'Canada', logoLink: 'mango.jpg', websiteURL: 'http://xkcd.com', email: 'ArnoldPalmer@golf.com', capacity:100 )
g.update_column(:logoLink, 'gc6.png')
g = GolfCourse.create!(name: 'Glen Eagle Golf Club', phone: 9058800131, addrStreetNum: 15731, addrUnitNum: nil, addrStreetName: 'Peel Regional Rd 50', addrCity: 'Bolton', addrPostalCode: 'L7E 3H9', addrCountry: 'Canada', logoLink: 'glen_eagle_golf_rula2y.gif', websiteURL: 'www.gleneagle.ca', email: 'GlenEagle@golf.com', capacity: 500 )
g = GolfCourse.create!(name: 'Don Valley Golf Course', phone: 4163922465, addrStreetNum: 4200, addrUnitNum: nil, addrStreetName: 'Yonge Street', addrCity: 'Toronto', addrPostalCode: 'M2P 1N9', addrCountry: 'Canada', logoLink: 'don_valley_ksmyfx.jpg', websiteURL: 'https://www1.toronto.ca/wps/portal/contentonly?vgnextoid=9a511b585c161410VgnVCM10000071d60f89RCRD', email: 'DonValley@golf.com', capacity: 500 )
g = GolfCourse.create!(name: 'Rosedale Golf Club', phone: 4164859321, addrStreetNum: 1901, addrUnitNum: nil, addrStreetName: 'Mt Pleasant Rd', addrCity: 'Toronto', addrPostalCode: 'M4N 2W3', addrCountry: 'Canada', logoLink: 'logo_yqmhll.png', websiteURL: 'http://www.rosedalegolf.org/', email: 'Rosedale@golf.com', capacity: 500 )
g = GolfCourse.create!(name: 'Glen Abbey Golf Club', phone: 9058441800, addrStreetNum: 1333, addrUnitNum: nil, addrStreetName: 'Dorval Drive', addrCity: 'Oakville', addrPostalCode: 'L6M 4G2', addrCountry: 'Canada', logoLink: 'getImage_cuwpsm.png', websiteURL: 'http://glenabbey.clublink.ca/', email: 'GlenAbbey@golf.com', capacity: 350)
g = GolfCourse.create!(name: 'Angus Glen Golf Club', phone: 9058870090, addrStreetNum: 10080, addrUnitNum: nil, addrStreetName: 'Kennedy Rd', addrCity: 'Markham', addrPostalCode: 'L6C 1N9', addrCountry: 'Canada', logoLink: 'logo-angus-black_btocmp.png', websiteURL: 'http://www.angusglen.com/', email: 'AngusGlen@golf.com', capacity: 450)
g = GolfCourse.create!(name: 'Osprey Valley Golf Course', phone: 5199279034, addrStreetNum: 19921, addrUnitNum: nil, addrStreetName: 'Main Street', addrCity: 'Caledon', addrPostalCode: 'L7K 1R1', addrCountry: 'Canada', logoLink: 'osprey_valley_zykt5k.jpg', websiteURL: 'https://www.ospreyvalleygolf.com/', email: 'OspreValley@golf.com', capacity: 450)

gcp = GolfCoursePerson.create(person_id: 2, golf_course_id: 1)
gcp = GolfCoursePerson.create(person_id: 2, golf_course_id: 2)
gcp = GolfCoursePerson.create(person_id: 4, golf_course_id: 3)
gcp = GolfCoursePerson.create(person_id: 12, golf_course_id: 4)
gcp = GolfCoursePerson.create(person_id: 17, golf_course_id: 5)
gcp = GolfCoursePerson.create(person_id: 21, golf_course_id: 6)
gcp = GolfCoursePerson.create(person_id: 7, golf_course_id: 7)
gcp = GolfCoursePerson.create(person_id: 19, golf_course_id: 8)
gcp = GolfCoursePerson.create(person_id: 27, golf_course_id: 9)
gcp = GolfCoursePerson.create(person_id: 12, golf_course_id: 10)
gcp = GolfCoursePerson.create(person_id: 11, golf_course_id: 11)
gcp = GolfCoursePerson.create(person_id: 4, golf_course_id: 12)

Host.create!(hostName: 'Golf Association of Hawaii', phone: 0010002222, email: 'gah@golf.com')
Host.create!(hostName: 'Society for Overworked Golf Players', phone: 0033302222, email: 'sogp@golf.com')
Host.create!(hostName: 'Make-A-Wish Foundation', phone: 0011112222, email: 'mawf@charity.com')
Host.create!(hostName: 'Kiwanis Club', phone: 1110002222, email: 'kc@charity.com')
Host.create!(hostName: 'Princess Margaret Cancer Foundation', phone: 4169466560, email: 'info@thepmcf.ca')
Host.create!(hostName: 'Golf Association of Ontario', phone: 9068521101, email: 'administration@gao.ca')

t = Tournament.create!(name: 'Make-A-Wish Foundation Spring Fundraiser', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("01/11/2017 12:00", "%m/%d/%Y %H:%M"), numGuests: 144, ticketsLeft: 100, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST',  registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 3, golf_course_id: 1)
t.update_column(:logoLink, 't1.png')
t = Tournament.create!(name: 'Golf Association of Hawaii Yearly 18H', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("12/25/2016 13:00", "%m/%d/%Y %H:%M"), numGuests: 120, ticketsLeft: 15, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 2, golf_course_id: 2)
t.update_column(:logoLink, 't2.png')
t = Tournament.create!(name: 'Society for Overworked Golf Player', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("06/06/2017 12:00", "%m/%d/%Y %H:%M"), numGuests: 220, ticketsLeft: 180, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 1, golf_course_id: 3)
t.update_column(:logoLink, 't3.png')
t = Tournament.create!(name: 'Florida Falls Residence Invitational', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("07/20/2018 10:00", "%m/%d/%Y %H:%M"), numGuests: 64, ticketsLeft: 32, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 1, golf_course_id: 6)
t.update_column(:logoLink, 'default_tournament_fhmvl4.jpg')
t = Tournament.create!(name: 'GOLF! Tykes and Tycoons', shortDesc: 'loremipsum', tournamentDate: DateTime.strptime("03/20/2017 10:00", "%m/%d/%Y %H:%M"), numGuests: 80, ticketsLeft: 72, privateURL: false, microSiteURL: '', logoLink: "puppy.jpg", language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("09/01/1999 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("09/01/2999 17:00", "%m/%d/%Y %H:%M"), host_id: 4, golf_course_id: 3)
t.update_column(:logoLink, 't5.png')
t = Tournament.create!(name: "Golf to Conquer Cancer", shortDesc: 'Supporting one of the Top 5 Cancer Research Centres in the World', numGuests: 250, privateURL: false, microSiteURL: 'http://www.golftoconquercancer.ca/', language: 'EN', currency: 'CAD', timeZone: 'EST', ticketsLeft: '230', registerStart: DateTime.strptime("01/01/2017 00:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("06/01/2017 00:00", "%m/%d/%Y %H:%M"), host_id: 5, golf_course_id: 10, tournamentDate: DateTime.strptime("06/12/2017 17:00", "%m/%d/%Y %H:%M")) 
t.update_column(:logoLink, 'HarryRosenLogo2_qhqysf.png')
t = Tournament.create!(name: 'Make-A-Wish Foundation Fall Fundraiser', shortDesc: 'Annual Tournament to Support One of the Largest Charities in the World', tournamentDate: DateTime.strptime("05/28/2017 08:00", "%m/%d/%Y %H:%M"), numGuests: 100, privateURL: false, microSiteURL: '', language: 'EN', currency: 'CAD', timeZone: 'EST',  registerStart: DateTime.strptime("02/01/2017 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("05/01/2017 17:00", "%m/%d/%Y %H:%M"), host_id: 3, golf_course_id: 8)
t.update_column(:logoLink, 'make-a-wish_onhdyr.png')
t = Tournament.create!(name: 'The TaylorMade Tussle', shortDesc: 'GTA AM Tour: Scarboro Golf & Country Club', tournamentDate: DateTime.strptime("05/09/2017 07:30", "%m/%d/%Y %H:%M"), numGuests: 150, privateURL: false, microSiteURL: '', language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("01/12/2017 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("03/15/2017 17:00", "%m/%d/%Y %H:%M"), host_id: nil, golf_course_id: nil, course_name: 'Scarboro Golf & Country Club', course_addr: '321 Scarborough Golf Club Rd, Toronto, ON M1J 3H2')
t.update_column(:logoLink, 'default_tournament_fhmvl4.jpg')
t = Tournament.create!(name: 'BMO World Elite Colliingwood Major', shortDesc: 'Sunday May 15 & Monday May 16 at Lora Bay & Georgian Bay Club', tournamentDate: DateTime.strptime("05/15/2017 13:30", "%m/%d/%Y %H:%M"), numGuests: 150, privateURL: false, microSiteURL: '', language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("01/12/2017 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("04/01/2017 17:00", "%m/%d/%Y %H:%M"), course_name: 'The Golf Club at Lora Bay', course_addr: '107 E Ride Dr, Thornbbury, ON N0H 2P0')
t.update_column(:logoLink, 'default_tournament_fhmvl4.jpg')
t = Tournament.create!(name: 'Team Ontario Cup', shortDesc: 'Apr 25th - Apr 26th At Grand Niagara Golf Course', tournamentDate: DateTime.strptime("04/25/2017 16:00", "%m/%d/%Y %H:%M"), numGuests: 55, privateURL: false, microSiteURL: 'https://gao.bluegolf.com/bluegolf/gao15/event/gao15237/index.htm', language: 'EN', currency: 'CAD', timeZone: 'EST', ticketsLeft: '55', registerStart: DateTime.strptime("03/25/2017 16:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("04/12/2017 01:00", "%m/%d/%Y %H:%M"), host_id: 6, golf_course_id: nil, course_name: 'Grand Niagara Golf Course', course_addr: '8547 Grassy Brook Rd., Niagara Falls')
t.update_column(:logoLink, 'GAO_spuftd.png')
t = Tournament.create!(name: 'Women\'s Champion of Champions', shortDesc: '2017 Women\'s Champion of Champions', tournamentDate: DateTime.strptime("05/19/2017 07:30", "%m/%d/%Y %H:%M"), numGuests: 16, privateURL: false, microSiteURL: 'https://gao.bluegolf.com/bluegolf/gao16/event/gao1614/index.htm', language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("01/25/2017 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("05/02/2017 17:00", "%m/%d/%Y %H:%M"), host_id: nil, golf_course_id: nil, course_name: 'Beverly Golf & Country Club', course_addr: '1211 2nd Concession W Copetown, ON')
t.update_column(:logoLink, 'default_tournament_fhmvl4.jpg')
t = Tournament.create!(name: 'IG Junior Spring Classic', shortDesc: 'Investors Group Spring Classic U19 Boys', tournamentDate: DateTime.strptime("05/21/2017 07:30", "%m/%d/%Y %H:%M"), numGuests: 32, privateURL: false, microSiteURL: 'https://gao.bluegolf.com/bluegolf/gao16/event/gao162/index.htm', language: 'EN', currency: 'CAD', timeZone: 'EST', registerStart: DateTime.strptime("01/25/2017 17:00", "%m/%d/%Y %H:%M"), registerEnd: DateTime.strptime("04/11/2017 17:00", "%m/%d/%Y %H:%M"), host_id: nil, golf_course_id: nil, course_name: 'Wooden Sticks Golf Club', course_addr: '40 Elgin Park Drive Uxbridge, ON L9P 1N2')
t.update_column(:logoLink, 'default_tournament_fhmvl4.jpg')

org = Organizer.create(person_id: 2, tournament_id: 3, permissions: 'FULL')
org = Organizer.create(person_id: 5, tournament_id: 1, permissions: 'FULL')
org = Organizer.create(person_id: 5, tournament_id: 2, permissions: 'FULL')
org = Organizer.create(person_id: 7, tournament_id: 2, permissions: 'FULL')
org = Organizer.create(person_id: 12, tournament_id: 2, permissions: 'FULL')
org = Organizer.create(person_id: 27, tournament_id: 3, permissions: 'FULL')
org = Organizer.create(person_id: 11, tournament_id: 4, permissions: 'FULL')
org = Organizer.create(person_id: 16, tournament_id: 5, permissions: 'FULL')
org = Organizer.create(person_id: 11, tournament_id: 5, permissions: 'FULL')
org = Organizer.create(person_id: 25, tournament_id: 6, permissions: 'FULL')
org = Organizer.create(person_id: 4, tournament_id: 6, permissions: 'FULL')
org = Organizer.create(person_id: 18, tournament_id: 7, permissions: 'FULL')
org = Organizer.create(person_id: 32, tournament_id: 7, permissions: 'FULL')
org = Organizer.create(person_id: 14, tournament_id: 7, permissions: 'FULL')
org = Organizer.create(person_id: 9, tournament_id: 7, permissions: 'FULL')
org = Organizer.create(person_id: 5, tournament_id: 8, permissions: 'FULL')
org = Organizer.create(person_id: 22, tournament_id: 9, permissions: 'FULL')
org = Organizer.create(person_id: 17, tournament_id: 10, permissions: 'FULL')
org = Organizer.create(person_id: 5, tournament_id: 11, permissions: 'FULL')
org = Organizer.create(person_id: 31, tournament_id: 12, permissions: 'FULL')

admin = Cloud9Person.create!(person_id: 1)

#ticket types
t = TicketType.create!(tournament_id: 1, name: 'Single', price: 50.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 1, name: 'Foursome', price: 175.00, numPlayers: 4)
t = TicketType.create!(tournament_id: 2, name: 'Single',  price: 50.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 2, name: 'Foursome',  price: 175.00, numPlayers: 4)
t = TicketType.create!(tournament_id: 3, name: 'Single', price: 50.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 3, name: 'Foursome',  price: 175.00, numPlayers: 4)
t = TicketType.create!(tournament_id: 4, name: 'Single',  price: 50.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 4, name: 'Foursome',  price: 175.00, numPlayers: 4)
t = TicketType.create!(tournament_id: 5, name: 'Single',  price: 32.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 5, name: 'Pair',  price: 55.00, numPlayers: 2)
t = TicketType.create!(tournament_id: 5, name: 'Foursome',  price: 100, numPlayers: 4)
t = TicketType.create!(tournament_id: 6, name: 'Single',  price: 25.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 6, name: 'Pair',  price: 45.00, numPlayers: 2)
t = TicketType.create!(tournament_id: 7, name: 'single',  price: 30.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 8, name: 'Single',  price: 20.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 8, name: 'Pair',  price: 35.00, numPlayers: 2)
t = TicketType.create!(tournament_id: 8, name: 'Foursome',  price: 60.00, numPlayers: 4)
t = TicketType.create!(tournament_id: 9, name: 'Single',  price: 35.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 9, name: 'Pair',  price: 55.00, numPlayers: 2)
t = TicketType.create!(tournament_id: 10, name: 'Single',  price: 25.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 11, name: 'Single',  price: 27.50, numPlayers: 1)
t = TicketType.create!(tournament_id: 12, name: 'Single',  price: 30.00, numPlayers: 1)
t = TicketType.create!(tournament_id: 12, name: 'Pair',  price: 60.00, numPlayers: 2)

#sponsorships
s = Sponsorship.create!(name: "Silver", price: 250.00, description: "", tournament_id: 1)
s = Sponsorship.create!(name: "Gold", price: 500.00, description: "", tournament_id: 1)
s = Sponsorship.create!(name: "Basic", price: 50.00, description: "", tournament_id: 2)
s = Sponsorship.create!(name: "Silver", price: 75.00, description: "", tournament_id: 3)
s = Sponsorship.create!(name: "Basic", price: 100.00, description: "", tournament_id: 4)
s = Sponsorship.create!(name: "Premium", price: 500.00, description: "", tournament_id: 4)
s = Sponsorship.create!(name: "Executive", price: 1000.00, description: "", tournament_id: 4)
s = Sponsorship.create!(name: "Silver", price: 55.00, description: "", tournament_id: 5)
s = Sponsorship.create!(name: "Gold", price: 250.00, description: "", tournament_id: 5)
s = Sponsorship.create!(name: "Silver", price: 150.00, description: "", tournament_id: 7)
s = Sponsorship.create!(name: "basic", price: 250.00, description: "", tournament_id: 8)
s = Sponsorship.create!(name: "Silver", price: 150.00, description: "", tournament_id: 10)
s = Sponsorship.create!(name: "Silver", price: 150.00, description: "", tournament_id: 11)
s = Sponsorship.create!(name: "Platinum", price: 5000.00, description: "", tournament_id: 11)

#Teams
team = Team.create(numPlayers: 4, tournament_id: 1, teeTime: DateTime.strptime("01/11/2017 14:00", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 1, teeTime: DateTime.strptime("01/11/2017 15:00", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 1, teeTime: DateTime.strptime("01/11/2017 16:00", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 2, teeTime: DateTime.strptime("12/25/2016 15:00", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 3, teeTime: DateTime.strptime("06/06/2017 13:00", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 3, teeTime: DateTime.strptime("06/06/2017 14:00", "%m/%d/%Y %H:%M"))

team = Team.create(numPlayers: 4, tournament_id: 4, teeTime: DateTime.strptime("07/20/2018 13:00", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 5, teeTime: DateTime.strptime("03/20/2017 12:30", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 6, teeTime: DateTime.strptime("06/12/2017 17:30", "%m/%d/%Y %H:%M"))

team = Team.create(numPlayers: 4, tournament_id: 7, teeTime: DateTime.strptime("05/28/2017 10:30", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 8, teeTime: DateTime.strptime("05/09/2017 12:30", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 8, teeTime: DateTime.strptime("05/09/2017 13:30", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 9, teeTime: DateTime.strptime("05/15/2017 14:30", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 9, teeTime: DateTime.strptime("05/15/2017 15:30", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 10, teeTime: DateTime.strptime("04/27/2017 11:30", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 12, teeTime: DateTime.strptime("05/21/2017 11:30", "%m/%d/%Y %H:%M"))
team = Team.create(numPlayers: 4, tournament_id: 12, teeTime: DateTime.strptime("05/21/2017 12:30", "%m/%d/%Y %H:%M"))

pl = Player.create(person_id: '1', tournament_id: '1', ticket_type_id: '1', team_id: 1)
pl = Player.create(person_id: '2', tournament_id: '1', ticket_type_id: '1', team_id: 1)
pl = Player.create(person_id: '3', tournament_id: '1', ticket_type_id: '1', team_id: 1)
pl = Player.create(person_id: '4', tournament_id: '1', ticket_type_id: '1', team_id: 1)
pl = Player.create(person_id: '6', tournament_id: '1', ticket_type_id: '1', team_id: 2)
pl = Player.create(person_id: '7', tournament_id: '1', ticket_type_id: '1', team_id: 2)
pl = Player.create(person_id: '8', tournament_id: '1', ticket_type_id: '1', team_id: 2)
pl = Player.create(person_id: '9', tournament_id: '1', ticket_type_id: '1', team_id: 2)
pl = Player.create(person_id: '10', tournament_id: '1', ticket_type_id: '1', team_id: 3)
pl = Player.create(person_id: '11', tournament_id: '1', ticket_type_id: '1', team_id: 3)
pl = Player.create(person_id: '12', tournament_id: '1', ticket_type_id: '1', team_id: 3)
pl = Player.create(person_id: '13', tournament_id: '1', ticket_type_id: '1', team_id: 3)
pl = Player.create(person_id: '1', tournament_id: '2', ticket_type_id: '1', team_id: 4)
pl = Player.create(person_id: '2', tournament_id: '2', ticket_type_id: '1', team_id: 4)
pl = Player.create(person_id: '10', tournament_id: '2', ticket_type_id: '1', team_id: 4)
pl = Player.create(person_id: '11', tournament_id: '2', ticket_type_id: '1', team_id: 4)
pl = Player.create(person_id: '3', tournament_id: '3', ticket_type_id: '1', team_id: 5)
pl = Player.create(person_id: '12', tournament_id: '3', ticket_type_id: '1', team_id: 5)
pl = Player.create(person_id: '4', tournament_id: '3', ticket_type_id: '1', team_id: 5)
pl = Player.create(person_id: '1', tournament_id: '3', ticket_type_id: '1', team_id: 5)
pl = Player.create(person_id: '2', tournament_id: '3', ticket_type_id: '1', team_id: 6)
pl = Player.create(person_id: '6', tournament_id: '4', ticket_type_id: '1', team_id: 7)
pl = Player.create(person_id: '7', tournament_id: '4', ticket_type_id: '1', team_id: 7)
pl = Player.create(person_id: '13', tournament_id: '4', ticket_type_id: '1', team_id: 7)
pl = Player.create(person_id: '2', tournament_id: '4', ticket_type_id: '1', team_id: 7)
pl = Player.create(person_id: '8', tournament_id: '5', ticket_type_id: '1', team_id: 8)
pl = Player.create(person_id: '9', tournament_id: '5', ticket_type_id: '1', team_id: 8)
pl = Player.create(person_id: '14', tournament_id: '6', ticket_type_id: '1', team_id: 9)
pl = Player.create(person_id: '21', tournament_id: '6', ticket_type_id: '1', team_id: 9)
pl = Player.create(person_id: '17', tournament_id: '6', ticket_type_id: '1', team_id: 9)
pl = Player.create(person_id: '6', tournament_id: '7', ticket_type_id: '1', team_id: 10)
pl = Player.create(person_id: '11', tournament_id: '7', ticket_type_id: '1', team_id: 10)
pl = Player.create(person_id: '14', tournament_id: '7', ticket_type_id: '1', team_id: 10)
pl = Player.create(person_id: '17', tournament_id: '7', ticket_type_id: '1', team_id: 10)
pl = Player.create(person_id: '21', tournament_id: '8', ticket_type_id: '1', team_id: 11)
pl = Player.create(person_id: '12', tournament_id: '8', ticket_type_id: '1', team_id: 11)
pl = Player.create(person_id: '9', tournament_id: '8', ticket_type_id: '1', team_id: 11)
pl = Player.create(person_id: '10', tournament_id: '8', ticket_type_id: '1', team_id: 11)
pl = Player.create(person_id: '17', tournament_id: '8', ticket_type_id: '1', team_id: 12)
pl = Player.create(person_id: '21', tournament_id: '9', ticket_type_id: '1', team_id: 13)
pl = Player.create(person_id: '22', tournament_id: '9', ticket_type_id: '1', team_id: 13)
pl = Player.create(person_id: '19', tournament_id: '9', ticket_type_id: '1', team_id: 13)
pl = Player.create(person_id: '27', tournament_id: '9', ticket_type_id: '1', team_id: 13)
pl = Player.create(person_id: '7', tournament_id: '9', ticket_type_id: '1', team_id: 14)
pl = Player.create(person_id: '8', tournament_id: '10', ticket_type_id: '1', team_id: 15)
pl = Player.create(person_id: '14', tournament_id: '10', ticket_type_id: '1', team_id: 15)
pl = Player.create(person_id: '21', tournament_id: '10', ticket_type_id: '1', team_id: 15)
pl = Player.create(person_id: '17', tournament_id: '12', ticket_type_id: '1', team_id: 16)
pl = Player.create(person_id: '14', tournament_id: '12', ticket_type_id: '1', team_id: 16)
pl = Player.create(person_id: '18', tournament_id: '12', ticket_type_id: '1', team_id: 16)
pl = Player.create(person_id: '24', tournament_id: '12', ticket_type_id: '1', team_id: 16)
pl = Player.create(person_id: '26', tournament_id: '12', ticket_type_id: '1', team_id: 17)
pl = Player.create(person_id: '3', tournament_id: '12', ticket_type_id: '1', team_id: 17)
pl = Player.create(person_id: '25', tournament_id: '12', ticket_type_id: '1', team_id: 17)
pl = Player.create(person_id: '16', tournament_id: '12', ticket_type_id: '1', team_id: 17)

sp = Sponsor.create(person_id: '2', tournament_id: '2')
sp = Sponsor.create(person_id: '2', tournament_id: '3')
sp = Sponsor.create(person_id: '3', tournament_id: '3')
sp = Sponsor.create(person_id: '7', tournament_id: '6')
sp = Sponsor.create(person_id: '15', tournament_id: '10')
sp = Sponsor.create(person_id: '21', tournament_id: '11')

